name: "test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '11'
        cache: maven
    - name: test local license
      uses: ./
      with:
        permitted-licenses: MIT,Apache-2.0,BSD
        base-path: ${{ github.workspace }}/test/java
    - name: second test
      run: cd test/java && license_finder
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2.0.0
      if: always()
      with:
        junit_files: "./test/java/license_finder_report.xml"
    - name: 'Upload Dependency Review Report'
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: license-finder-report
        path: ./test/java/license_finder_report.xml
